topic:
  name: topic-name
  partitions-num: 6
  replication-factor: 3
server:
  port: 9192
spring:
  kafka:
    bootstrap-servers:
      - bootstrap-ip
    properties:
      # CCloud broker connection parameters
#      ssl.endpoint.identification.algorithm: https
#      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      retry.backoff.ms: 500
#      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="ccloud_key" password="ccloud_secret";   (2)
#      security.protocol: SASL_SSL

      # CCloud Schema Registry Connection parameter
      schema.registry.url: schema-registry-address
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: login:password
    consumer:
      group-id: spring_boot_group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info

send:
  kafka:
    message: 10000